export { AboutFolio } from './AboutFolio'
export { AboutMe } from './AboutMe'
export { Contact } from './Contact'
export { Experience } from './Experience'
export { Home } from './Home'
export { Tech } from './Tech'
